// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFf799ii6f7ESx-LfilniVMp43tg9qK5k',
    appId: '1:239810208667:web:df8c3566d1d710ab7af73e',
    messagingSenderId: '239810208667',
    projectId: 'flutter-recipe-cook',
    authDomain: 'flutter-recipe-cook.firebaseapp.com',
    storageBucket: 'flutter-recipe-cook.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCinOmVDd0AcYuuqvYs1i74PBb8GzuZaeQ',
    appId: '1:239810208667:android:c92d941a58162f077af73e',
    messagingSenderId: '239810208667',
    projectId: 'flutter-recipe-cook',
    storageBucket: 'flutter-recipe-cook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Fi9q7RstWh7BZcvG2-Oii4F88ufFGPA',
    appId: '1:239810208667:ios:1dce07e9e469c73d7af73e',
    messagingSenderId: '239810208667',
    projectId: 'flutter-recipe-cook',
    storageBucket: 'flutter-recipe-cook.firebasestorage.app',
    iosBundleId: 'com.example.recipeCook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Fi9q7RstWh7BZcvG2-Oii4F88ufFGPA',
    appId: '1:239810208667:ios:1dce07e9e469c73d7af73e',
    messagingSenderId: '239810208667',
    projectId: 'flutter-recipe-cook',
    storageBucket: 'flutter-recipe-cook.firebasestorage.app',
    iosBundleId: 'com.example.recipeCook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFf799ii6f7ESx-LfilniVMp43tg9qK5k',
    appId: '1:239810208667:web:aaaaf91b9aea2af07af73e',
    messagingSenderId: '239810208667',
    projectId: 'flutter-recipe-cook',
    authDomain: 'flutter-recipe-cook.firebaseapp.com',
    storageBucket: 'flutter-recipe-cook.firebasestorage.app',
  );
}
